### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by mstuttgart** [pynocchio/pynocchio-translations#1]
Add translation to Pynocchio Comic Reader

- [x] en-US
- [x] pt-BR
- [x] pl-PL
- [x] pt-PT
- [x] es
- [x] fr
- [x] nl-NL
- [ ] ja-JP

and others :)

**Comment by kRkk** [comment]
Can I add Polish translation?

**Comment by mstuttgart** [comment]
@kRkk Yes! :+1:

**Comment by kRkk** [comment]
Polish file must be saved as `pl-pl.ts` or `pl.ts`?

**Comment by mstuttgart** [comment]
Save as `pl-pl.ts`. Thanks!

**Comment by kRkk** [comment]
I read in [readme.md](../blob/master/README.md) and saw that I have to have installed QtLinguist, but I edited this with Atom :atom:

**Comment by mstuttgart** [comment]
@kRkk no problem. QtLinguist help to translate, but the `.t`s file is a `xml` file. Then, you can edit it in any editor :)

**Comment by rodrigets** [comment]
Vou adicionar a tradução em ES. ( espanhol )

**Comment by bfaguer** [comment]
I can work on the French one if you want.

**Comment by mstuttgart** [comment]
Hi @bfaguer. Yes :+1:

**Comment by Tocive** [comment]
I've added a Pull Request for a Dutch translation :D
